### ISSUE TITLE
Will not run correctly on Google Colab.

### ISSUE THREAD

**Issue by hbenthow** [TheLastBen/fast-stable-diffusion#2]
When I run your version of either  Automatic1111 or Hlky on Colab, I get the following error when trying to generate an image:

"RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1."

**Comment by TheLastBen** [comment]
What is the GPU used in your Colab ?

**Comment by hbenthow** [comment]
> What is the GPU used in your Colab ?

I'm not sure. How can I find out?

**Comment by hbenthow** [comment]
I tried to run it again, and noticed that Colab gave me the warning "Warning: you are connected to a GPU runtime, but not utilizing the GPU." Could that be relevant, and if so, how can it be fixed?

**Comment by TheLastBen** [comment]
remove the folder "sd" or "stable-diffusion-webui" from your gdrive(also from trash) and restart the colab, make sure you use the latest colab from github, because the issue has been fixed last night.

**Comment by hbenthow** [comment]
> remove the folder "sd" or "stable-diffusion-webui" from your gdrive(also from trash) and restart the colab, make sure you use the latest colab from github, because the issue has been fixed last night.

That fixed it! Thank you.

**Comment by hbenthow** [comment]
By the way, do you know which cells need to be run in every session and which ones only need to be run the first time? I know "Model Download" cell only needs to be run in the first session, but I'm not sure if any others only need to be run once as well.

**Comment by TheLastBen** [comment]
Run the whole colab, it will automatically skip the unnecessary steps, but you have to run all the cells respectively from the beginning.

**Comment by hbenthow** [comment]
> Run the whole colab, it will automatically skip the unnecessary steps, but you have to run all the cells respectively from the beginning.

Thank you.
