### ISSUE TITLE
CUDA ERROR: 

### ISSUE THREAD

**Issue by LIQUIDMIND111** [TheLastBen/fast-stable-diffusion#2025]
This morning and afternoon was working alright, now i have this error:

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 60.00 MiB (GPU 0; 14.75 GiB total capacity; 13.24 GiB already allocated; 36.81 MiB free; 13.35 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Progress:|                         |  1% 20/3500 [00:35<1:43:13,  1.78s/it, loss=0.00488, lr=1.99e-6]

Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.9/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.9/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)

subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--image_captions_filename', '--train_only_unet', '--save_starting_step=500', '--save_n_steps=0', '--Session_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/YwzAxidaXwY2', '--pretrained_model_name_or_path=/content/stable-diffusion-v1-5', '--instance_data_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/YwzAxidaXwY2/instance_images', '--output_dir=/content/models/YwzAxidaXwY2', '--captions_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/YwzAxidaXwY2/captions', '--instance_prompt=', '--seed=601691', '--resolution=768', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--use_8bit_adam', '--learning_rate=2e-06', '--lr_scheduler=linear', '--lr_warmup_steps=0', '--max_train_steps=3500']' returned non-zero exit status 1.

Something went wrong

**Comment by LIQUIDMIND111** [comment]
it says something about 

"If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation", 

is this something that i need to do?

**Comment by TheLastBen** [comment]
have you trained with the same settings before?

**Comment by LIQUIDMIND111** [comment]
> 

actually yes, since last model was almost perfect....... i even resumed training many times.... then after trying to make a NEW model, i get this error, i even deleted my temp history and files, and refreshed CHROME and nothing......

**Comment by LIQUIDMIND111** [comment]
> have you trained with the same settings before?

ok seems its working now, i found out i had 1 photo that missed cropping, and that was the error

**Comment by TheLastBen** [comment]
always use the smart_crop setting

**Comment by LIQUIDMIND111** [comment]
@TheLastBen ok let's say I want to train a model on "football players or people eating at a restaurant", 

Since there are many faces, do i train this model as a FACE or STYLE in this occasion? Use STYLE OPTION here?

**Comment by TheLastBen** [comment]
If you want to train on a single person, you need images that display only that person

**Comment by LIQUIDMIND111** [comment]
Ok.. How does external caption works? Is it for adding more tokens to the
original images main token? Like if my photos are named hyrgb(1). jpg etc,
captions will add more description? Like WHAT IS THE PHOTO ABOUT. Is that
how it works?

If the photo is about a woman in a dress, I can add external captions about
that photo in particular, and mention that the photo is about a woman in a
dress?

**Comment by LIQUIDMIND111** [comment]
> for example 1.jpg is a picture of a dog inside a car, to add external captions to this image, create a file named 1.txt, put the description inside and upload it along with the image using the instance images cell. make sure all images have the same extension (all jpg or all png ..)

hello, yes i tried doing a small batch, but it RAISES A LOT the training time!!! THanks. 👍
