### ISSUE TITLE
CUDA error

### ISSUE THREAD

**Issue by Terenzio-Avantaggiato** [TheLastBen/fast-stable-diffusion#2628]
I downloaded the latest version of the notebook this morning, but I have this error which appears every time I perform a task:

RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.

**Comment by junwoochoi2** [comment]
Exactly the same problem happened to me. The problem does not occur especially when the GPU is set to T4, but the problem occurs when it is set to V100.

**Comment by Terenzio-Avantaggiato** [comment]
> Exactly the same problem happened to me. The problem does not occur especially when the GPU is set to T4, but the problem occurs when it is set to V100.

I only tried with V100... it's the GPU I usually use. I'll try A100 later.

**Comment by kashyapjha** [comment]
Same with me. Not working on V100.

**Comment by scorpi0n81** [comment]
Getting same error. Tried with latest notebook as well. @TheLastBen please help!

**Comment by Nissy0922** [comment]
I also tried it on the latest notebook, but the same error occurs on anything other than T4.

I wanted to try it with A100, but for some reason I couldn't connect.

**Comment by TheLastBen** [comment]
xformers was compiled for T4 and A100, I'll add support for V100 later

**Comment by Nissy0922** [comment]
thank you for your reply.

I tried it on A100 earlier and was able to create it successfully.

V100 still didn't work, so I'm looking forward to your support.

**Comment by Sashimi-jp** [comment]
> xformers was compiled for T4 and A100, I'll add support for V100 later

Thank you. I greatly appreciate it.

**Comment by scorpi0n81** [comment]
> xformers was compiled for T4 and A100, I'll add support for V100 later

Will eagerly wait for that. V100 is the best in terms of speed to cost ratio. T4 too slow and A100 hardly gets available.

**Comment by TheLastBen** [comment]
it should work for V100 now

**Comment by Nissy0922** [comment]
When I tried it on V100 now, no error occurred.

Thank you for your response.

**Comment by Terenzio-Avantaggiato** [comment]
Thank you so much!
_______________________________________________________________
*Avantaggiato Terenzio* [TRAGIX]


Il giorno mar 24 ott 2023 alle ore 20:02 Ben ***@***.***> ha
scritto:

**Comment by scorpi0n81** [comment]
> it should work for V100 now

Works like a charm - thanks a ton!!
