### ISSUE TITLE
dreambooth training broken

### ISSUE THREAD

**Issue by nerdvegas** [TheLastBen/fast-stable-diffusion#549]
```
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DFALT_TENSOR_OP)`
Progress:|                         |  0% 3/4500 [00:11<4:38:08,  3.71s/it, loss=0.167, lr=2e-6]
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--image_captions_filename', '--train_text_encoder', '--save_starting_step=3000', '--stop_text_encoder_training=4500', '--save_n_steps=500', '--Session_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/shomewood', '--pretrained_model_name_or_path=/content/stable-diffusion-v1-5', '--instance_data_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/shomewood/instance_images', '--output_dir=/content/models/shomewood', '--instance_prompt=', '--seed=190452', '--resolution=512', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--use_8bit_adam', '--learning_rate=2e-6', '--lr_scheduler=polynomial', '--lr_warmup_steps=0', '--max_train_steps=4500']' returned non-zero exit status 1.
Something went wrong
```

**Comment by TheLastBen** [comment]
If you're using premium GPU with Google Colab, uncheck the box "fp16"

**Comment by nerdvegas** [comment]
Did something change? I've been using fp16 with premium GPU successfully until now, thx.

**Comment by TheLastBen** [comment]
because I automatically disabled fp16 for A100 even when fp16 is checked, I removed the code because I tried with an A100 and it worked, but apparently, not for everyone.
