### ISSUE TITLE
GPU out of memory when about to train text encoder

### ISSUE THREAD

**Issue by Taikakim** [TheLastBen/fast-stable-diffusion#986]
I was wondering why sometimes there is no text encodering phase. Now I happened to see when the class images were created for a resumed run, the notebook was about to start training the text encoder, but gave me a red GPU out of memory instead, but then that output was wiped, and a clean normal lookin Unet training started. I was wondering why my trained models look very bad. Maybe this is the solution? I'm not even sure what GPU I'm on, since I have some compute units left from before I closed my Pro account. Now the session manager shows that I'm using 12.17 GB of GPU memory, so I guess I'm not on a K80 but a T4 probably?

Does the amout of images (I have 40 now) affect the amount of GPU memory needed for the text encoder training?

**Comment by TheLastBen** [comment]
try again with the latest colab https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb

**Comment by Taikakim** [comment]
I'm not sure how recent mine is, but not more than a few days.

Today I tried with 25 images instead of 40 with 2.1 768px, and it works beautifully with even this same version of notenook than before. Text encoder training took just below 15GB, so maybe that was the issue? Now finally the results I'm getting are not all over and glitchy as hell :)
